"""Initial  Migration

Revision ID: 1ed56482db83
Revises: 
Create Date: 2026-03-01 18:32:31.833299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ed56482db83'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_eventos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_origem', sa.String(length=45), nullable=False),
    sa.Column('ip_destino', sa.String(length=45), nullable=True),
    sa.Column('porta_origem', sa.Integer(), nullable=True),
    sa.Column('porta_destino', sa.Integer(), nullable=True),
    sa.Column('protocolo', sa.String(length=20), nullable=True),
    sa.Column('regras', sa.String(), nullable=True),
    sa.Column('severidade', sa.Enum('CRITICA', 'ALTA', 'MEDIA', 'BAIXA', name='severidade'), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'MITIGADO', 'IGNORADO', name='status'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ANALISTA', 'OPERADOR', name='user_roles'), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('alertas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('ip_origem', sa.String(length=45), nullable=False),
    sa.Column('ip_destino', sa.String(length=45), nullable=False),
    sa.Column('protocolo', sa.String(length=20), nullable=True),
    sa.Column('porta_de_comunicacao', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['log_eventos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analises_ia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('classificacao', sa.String(), nullable=True),
    sa.Column('confianca', sa.Float(), nullable=True),
    sa.Column('detalhes', sa.JSON(), nullable=True),
    sa.Column('analisado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['log_eventos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ips_bloqueados',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bloqueado_por', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('ip_bloqueado', sa.String(length=45), nullable=False),
    sa.Column('motivo', sa.String(), nullable=True),
    sa.Column('bloqueado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alertas.id'], ),
    sa.ForeignKeyConstraint(['bloqueado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_bloqueado')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ips_bloqueados')
    op.drop_table('analises_ia')
    op.drop_table('alertas')
    op.drop_table('usuarios')
    op.drop_table('log_eventos')
    # ### end Alembic commands ###
